from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_fri(object):
    def setupUi(self, add_fri):
        add_fri.setObjectName("add_fri")
        add_fri.resize(426, 653)
        self.lineEdit_add = QtWidgets.QLineEdit(add_fri)
        self.lineEdit_add.setGeometry(QtCore.QRect(40, 410, 251, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.lineEdit_add.sizePolicy().hasHeightForWidth())
        self.lineEdit_add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.lineEdit_add.setFont(font)
        self.lineEdit_add.setObjectName("lineEdit_add")
        self.pushButton__add = QtWidgets.QPushButton(add_fri)
        self.pushButton__add.setGeometry(QtCore.QRect(40, 540, 361, 91))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        self.pushButton__add.setFont(font)
        self.pushButton__add.setObjectName("pushButton__add")
        self.dateEdit__add = QtWidgets.QDateEdit(add_fri)
        self.dateEdit__add.setGeometry(QtCore.QRect(190, 470, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.dateEdit__add.setFont(font)
        self.dateEdit__add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateEdit__add.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit__add.setObjectName("dateEdit__add")
        self.label_add = QtWidgets.QLabel(add_fri)
        self.label_add.setGeometry(QtCore.QRect(30, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.label_add.setFont(font)
        self.label_add.setObjectName("label_add")
        self.listWidget_add = QtWidgets.QListWidget(add_fri)
        self.listWidget_add.setGeometry(QtCore.QRect(30, 70, 371, 321))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.listWidget_add.setFont(font)
        self.listWidget_add.setObjectName("listWidget_add")

        self.retranslateUi(add_fri)
        QtCore.QMetaObject.connectSlotsByName(add_fri)

    def retranslateUi(self, add_fri):
        _translate = QtCore.QCoreApplication.translate
        add_fri.setWindowTitle(_translate("add_fri", "Заполнение холодильника"))
        self.pushButton__add.setText(_translate("add_fri", "Добавить"))
        self.label_add.setText(_translate("add_fri", "Вы добавили:"))
