from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(300, 60, 300, 100))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(42)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_1.setFont(font)
        self.label_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setLineWidth(3)
        self.label_1.setMidLineWidth(0)
        self.label_1.setObjectName("label_1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 200, 541, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout1.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout1.setSpacing(10)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.pushButton_addfri = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addfri.sizePolicy().hasHeightForWidth())
        self.pushButton_addfri.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.pushButton_addfri.setFont(font)
        self.pushButton_addfri.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_addfri.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_addfri.setObjectName("pushButton_addfri")
        self.verticalLayout1.addWidget(self.pushButton_addfri)
        self.pushButton_myfri = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_myfri.sizePolicy().hasHeightForWidth())
        self.pushButton_myfri.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.pushButton_myfri.setFont(font)
        self.pushButton_myfri.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_myfri.setObjectName("pushButton_myfri")
        self.verticalLayout1.addWidget(self.pushButton_myfri)
        self.pushButton_pastfri = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pastfri.sizePolicy().hasHeightForWidth())
        self.pushButton_pastfri.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.pushButton_pastfri.setFont(font)
        self.pushButton_pastfri.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_pastfri.setObjectName("pushButton_pastfri")
        self.verticalLayout1.addWidget(self.pushButton_pastfri)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "MY FRI"))
        self.pushButton_addfri.setText(_translate("MainWindow", "Заполнить холодильник"))
        self.pushButton_myfri.setText(_translate("MainWindow", "Мой холодильник"))
        self.pushButton_pastfri.setText(_translate("MainWindow", "Прошлое холодильника"))
